#!/usr/bin/python
import subprocess
import argparse


def split_mapfile(mapfile, number):
    
    for i in range(number):
        cmd = (
            f"sed -n '{16*i + 1},{16* (i+1)}p' {mapfile} > new_mapfile{i+1}"
        )
        subprocess.check_call(cmd, shell=True)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="split mapfile")
    parser.add_argument("--mapfile", help="mapfile", required=True)
    parser.add_argument("--number", help="mapfile number", default=6, type=int)
    args = parser.parse_args()
    split_mapfile(args.mapfile, args.number)